### ISSUE TITLE
Mute/timeout message does not show up at time of timeout or at all

### ISSUE THREAD

**Issue by GiveMeAnOnion** [airforce270/CytubeBot#94]
The new timeout message is not displayed directly after being timed out, or does not appear at all.

Reference- Got timed out one day prior and was not timed out when I left, but got this messages after I joined back: https://imgur.com/75OlSvy. Then I did $poof to test if it would show up, but it did not. (Only a few minutes ago, might show up later.)

**Comment by airforce270** [comment]
Just want to confirm timeline: 

- Was timed out
- Left server
- Came back after timeout should have expired
- Bot didn't remove timeout automatically

Is this right?

**Comment by GiveMeAnOnion** [comment]
No, the timeout expired a while before I left the server. I came back, I was not timed out, but the message that I had been muted (the one in the imgur link) appeared as if I did.

**Comment by airforce270** [comment]
Hmm, I see. 

I think the issue is that the bot only unmutes based on the current user list - the unmute (un-timeout) doesn't actuate until you rejoin. 

So you see that message as you're still muted when you rejoin. The bot knows you shouldn't still be muted, but hasn't done it yet.

Possible to fix by keeping track of timed out users separately from the user list itself, and using that to do unmutes instead of (or in addition to) current user list

**Comment by airforce270** [comment]
Seems like its not possible to fix this one due to cytube architecture - can't untimeout until user rejoins. Should be <=10s of mute time after rejoining
